### ISSUE TITLE
PuppeteerPlugin threw an error - address already in use

### ISSUE THREAD

**Issue by rubydev** [apify/browser-pool#48] opened 2021-09-10 08:37 UTC
When we kicked off multiple runs on Apify platform, two actors threw same exception in similar time (and main function of actor failed). Both runs contained same IP address and port in log file. Session ID was different.

node: 14
apify SDK: 1.3.4
browser-pool: 1.2.0-beta.1
puppeteer: 10.2.0

```
2021-09-09T11:45:52.929Z Error: BrowserPool: Could not anonymize proxyUrl: http://groups-RESIDENTIAL,session-session_XXX,country-US:*********@X.X.X.X:XXXX/. Reason: listen EADDRINUSE: address already in use ::.
2021-09-09T11:45:52.931Z at PuppeteerPlugin._getAnonymizedProxyUrl (/home/myuser/app/node_modules/browser-pool/dist/abstract-classes/browser-plugin.js:137:19)
2021-09-09T11:45:52.933Z at runMicrotasks ()
2021-09-09T11:45:52.935Z at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-09-09T11:45:52.936Z at async PuppeteerPlugin._addProxyToLaunchOptions (/home/myuser/app/node_modules/browser-pool/dist/puppeteer/puppeteer-plugin.js:45:29)
2021-09-09T11:45:52.939Z at async PuppeteerPlugin.launch (/home/myuser/app/node_modules/browser-pool/dist/abstract-classes/browser-plugin.js:93:13)
2021-09-09T11:45:52.941Z at async BrowserPool._launchBrowser (/home/myuser/app/node_modules/browser-pool/dist/browser-pool.js:417:29)
2021-09-09T11:45:52.942Z at async BrowserPool.newPage (/home/myuser/app/node_modules/browser-pool/dist/browser-pool.js:185:33)
2021-09-09T11:45:52.944Z at async PuppeteerCrawler._handleRequestFunction (/home/myuser/app/node_modules/apify/build/crawlers/browser_crawler.js:306:22)
```

**Comment by B4nan** [comment] 2021-09-10 08:41
Can you please test this with latest versions? browser-pool 2.0.2 has a fix for race condition in the `newPage` method, so it might be very well already fixed.

cc @szmarczak

**Comment by szmarczak** [comment] 2021-09-10 09:12
@B4nan This is very different. The race condition I fixed was causing too many tabs open than max allowed.

**Comment by szmarczak** [comment] 2021-09-10 12:59
It looks like it failed to generate the port. Are you able to reproduce the issue?

**Comment by rubydev** [comment] 2021-09-13 08:31
Hi, I’m not able reproduce the issue again - it happened only once. I will let you know, if it will happen again.

**Comment by szmarczak** [comment] 2021-09-22 07:21
This is definitely port exhaustion. I'm getting the same error via:

```js
const http = require('http');

const listen = () => {
    http.createServer().listen(0, listen);
};

listen();
```

```
Error: listen EADDRINUSE: address already in use ::
    at Server.setupListenHandle [as _listen2] (node:net:1319:16)
    at listenInCluster (node:net:1367:12)
    at Server.listen (node:net:1454:7)
    at Server.listen (/home/szm/Desktop/proxy-chain/ex.js:4:25)
    at Object.onceWrapper (node:events:513:28)
    at Server.emit (node:events:394:28)
    at emitListeningNT (node:net:1353:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1346:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::'
}
```

**Comment by rubydev** [comment] 2021-09-22 07:28
@szmarczak Week ago it happened again. And before it happened, in log was a lot errors like this:

<img width="1179" alt="screenshot 386" src="https://user-images.githubusercontent.com/599358/134300515-7962356d-1bbb-41a4-918b-b63ad95b933d.png">

Can't it be related with this? https://github.com/apify/browser-pool/issues/32

**Comment by szmarczak** [comment] 2021-10-04 07:04
This should be fixed now.

**Closed** 2022-04-25 00:59 UTC
Labels: bug
